translation_unit ::= { external_declaration } ;
external_declaration ::= function_definition | declaration ;
function_definition ::= declaration_specifiers declarator compound_statement ;
declaration ::= declaration_specifiers [ init_declarator_list ] ";" | static_assert_declaration | ";" ;
declaration_specifiers ::= declaration_specifier { declaration_specifier } ;
declaration_specifier ::= storage_class_specifier | type_specifier | type_qualifier | function_specifier | alignment_specifier ;
declarator ::= [ pointer ] direct_declarator ;
compound_statement ::= "{" { declaration_or_statement } "}" ;
declaration_or_statement ::= declaration | statement ;
init_declarator_list ::= init_declarator { "," init_declarator } ;
init_declarator ::= declarator [ "=" initializer ] ;
static_assert_declaration ::= "_Static_assert" "(" constant_expression "," string_literal ")" ";" ;
storage_class_specifier ::= "typedef" | "extern" | "static" | "_Thread_local" | "auto" | "register" ;
type_specifier ::= "void" | "char" | "short" | "int" | "long" | "float" | "double" | "signed" | "unsigned" | "_Bool" | "_Imaginary" | "_Complex"
                 | atomic_type_specifier | struct_or_union_specifier | enum_specifier | typedef_name ;
typedef_name ::= identifier ;
type_qualifier ::= "const" | "restrict" | "volatile" | "_Atomic" ;
function_specifier ::= "inline" | "_Noreturn" ;
alignment_specifier ::= "_Alignas" "(" ( type_name | constant_expression ) ")" ;
pointer ::= "*" [ type_qualifier_list ] [ pointer ] ;
direct_declarator ::= identifier | "(" declarator ")"
                    | direct_declarator "[" [ "static" [ type_qualifier_list ] | type_qualifier_list [ "static" ] ] assignment_expression "]"
                    | direct_declarator "(" [ parameter_type_list ] ")"
                    | direct_declarator "[" [ type_qualifier_list ] [ "*" ] "]" ;
initializer_list ::= [ designation ] initializer { "," [ designation ] initializer } ;
initializer ::= "{" initializer_list [ "," ] "}" | assignment_expression ;
constant_expression ::= conditional_expression ;
atomic_type_specifier ::= "_Atomic" "(" type_name ")" ;
struct_or_union_specifier ::= ( "struct" | "union" ) ( [ identifier ] "{" struct_declaration_list "}" | identifier ) ;
struct_declaration_list ::= struct_declaration { struct_declaration } ;
struct_declaration ::= specifier_qualifier_list [ struct_declarator_list ] ";" | static_assert_declaration ;
enum_specifier ::= "enum" ( [ identifier ] "{" enumerator_list [ "," ] "}" | identifier ) ;
enumerator_list ::= enumerator { "," enumerator } ;
enumerator ::= enumeration_constant [ "=" constant_expression ] ;
enumeration_constant ::= identifier ;
type_name ::= specifier_qualifier_list [ abstract_declarator ] ;
specifier_qualifier_list ::= specifier_qualifier { specifier_qualifier } ;
specifier_qualifier ::= type_specifier | type_qualifier ;
abstract_declarator ::= [ pointer ] direct_abstract_declarator | pointer;
direct_abstract_declarator ::= "(" abstract_declarator ")"
                           | [ direct_abstract_declarator ] "[" [ "static" [ type_qualifier_list ] | type_qualifier_list [ "static" ] ] assignment_expression "]"
                           | [ direct_abstract_declarator ] "(" [ parameter_type_list ] ")"
                           | [ direct_abstract_declarator ] "[" [ "*" ] "]" ;
struct_declarator_list ::= struct_declarator { "," struct_declarator } ;
type_qualifier_list ::= type_qualifier { type_qualifier } ;
parameter_type_list ::= parameter_list [ "," "..." ] ;
struct_declarator ::= [ declarator ] ":" constant_expression | declarator ;
assignment_operator ::= "="  | "*="  | "/="  | "%="  | "+="  | "-="  | "<<="  | ">>="  | "&="  | "^="  | "|=" ;
parameter_list ::= parameter_declaration { "," parameter_declaration } ;
parameter_declaration ::= declaration_specifiers [ declarator | abstract_declarator ] ;
expression ::= assignment_expression { "," assignment_expression } ;
assignment_expression ::= conditional_expression | unary_expression assignment_operator assignment_expression ;
conditional_expression ::= logical_or_expression [ "?" expression ":" conditional_expression] ;
logical_or_expression ::= logical_and_expression { "||" logical_and_expression } ;
logical_and_expression ::= inclusive_or_expression { "&&" inclusive_or_expression } ;
inclusive_or_expression ::= exclusive_or_expression { "|" exclusive_or_expression } ;
exclusive_or_expression ::= and_expression { "^" and_expression } ;
and_expression ::= equality_expression { "&" equality_expression } ;
equality_expression ::= relational_expression { ( "==" | "!=" ) relational_expression } ;
relational_expression ::= shift_expression { ( "<" | ">" | "<=" | ">=" ) shift_expression } ;
shift_expression ::= additive_expression { ("<<" | ">>") additive_expression } ;
additive_expression ::= multiplicative_expression { ("+" | "-") multiplicative_expression } ;
multiplicative_expression ::= cast_expression { ("*" | "/" | "%") cast_expression } ;
cast_expression ::= unary_expression | "(" type_name ")" cast_expression ;
unary_expression ::= postfix_expression | ( "++" | "--" | "sizeof" ) unary_expression | unary_operator cast_expression | ( "sizeof" | "_Alignof" ) "(" type_name ")" ;
postfix_expression ::= primary_expression | "(" type_name ")" "{" initializer_list [ "," ] "}"
                   | postfix_expression ( "[" expression "]" | "(" [ argument_expression_list ] ")" | ( "." | "->" ) identifier | ( "++" | "--" ) ) ;
unary_operator ::= "&" | "*" | "+" | "-" | "~" | "!" ;
primary_expression ::= identifier | constant | string | "(" expression ")" | generic_selection ;
argument_expression_list ::= assignment_expression { "," assignment_expression } ;
constant ::= integer_constant | character_constant | floating_constant | enumeration_constant ;
string ::= string_literal ;
generic_selection ::= "_Generic" "(" assignment_expression "," generic_assoc_list ")" ;
generic_assoc_list ::= generic_association {"," generic_association};
generic_association ::= ( type_name | "default" ) ":" assignment_expression ;
designation ::= designator_list "=" ;
designator_list ::= designator { designator } ;
designator ::= "[" constant_expression "]" | "." identifier ;
statement ::= labeled_statement | compound_statement | expression_statement | selection_statement | iteration_statement | jump_statement ;
labeled_statement ::= ( identifier | "case" constant_expression | "default" ) ":" statement ;
expression_statement ::= [ expression ] ";" ;
selection_statement ::= "if" "(" expression ")" statement [ "else" statement ] | "switch" "(" expression ")" statement ;
iteration_statement ::= "while" "(" expression ")" statement | "do" statement "while" "(" expression ")" ";"
                     | "for" "(" ( [ expression ] ";" | declaration ) [ expression ] ";" [ expression ] ")" statement ;
jump_statement ::= ( "goto" identifier | "continue" | "break" | "return" [ expression ] ) ";" ;

integer_constant ::= ( decimal | octal | hexadecimal | binary ) ( [ "u" | "U" ] ["l" | "L" | "ll" | "LL"] | ["l" | "L" | "ll" | "LL"] [ "u" | "U" ] ) ;
decimal ::= ( "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ) { digit } ;
octal ::= "0" { "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" } ;
hexadecimal ::= ( "0x" | "0X" ) hex_digit { hex_digit } ;
binary ::= ( "0b" | "0B" ) ( "0" | "1" ) { "0" | "1" } ;
floating_constant ::= ( decimal_floating | hexadecimal_floating ) [ "f" | "F" | "l" | "L" ] ;
decimal_floating ::= digit { digit } "." { digit } [ exponent ] | "." digit { digit } [ exponent ] | digit { digit } exponent ;
exponent ::= ( "e" | "E" ) [ "+" | "-" ] digit { digit } ;
hexadecimal_floating ::= ( "0x" | "0X" ) ( hex_digit { hex_digit } "." | "." hex_digit | hex_digit ) { hex_digit } ( "p" | "P" ) [ "+" | "-" ] digit { digit }
digit ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
hex_digit ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "a" | "b" | "c" | "d" | "e" | "f" | "A" | "B" | "C" | "D" | "E" | "F" ;
oct_digit ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" ;
character_constant ::= "'" ( c_char | escape_sequence ) "'" ;
escape_sequence ::= "\\" ( "a" | "b" | "f" | "n" | "r" | "t" | "v" | "\\" | "'" | "\"" | "?" | oct_digit [ oct_digit ] [ oct_digit ] | "x" hex_digit { hex_digit } | unicode_escape_sequence ) ;
unicode_escape_sequence ::= "U" hex_digit hex_digit hex_digit hex_digit hex_digit hex_digit hex_digit hex_digit | "u" hex_digit hex_digit hex_digit hex_digit ;
